### ISSUE TITLE
cu5t0mPe0 - Users can mint tokens for free

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#79]
cu5t0mPe0

high

# Users can mint tokens for free

## Summary

`Edition.sol` does not check whether the user has sent the amount to the current contract

## Vulnerability Detail

Under the normal process, the user sends eth to Edition, and then sends eth to FeeManager for distribution. However, if the FeeManager contract itself has some unexpected amounts, the user can call the Edition::mint() function for free to mint tokens. .

poc:

add it and run it in Edition.t.sol

```solidity
    function test_Freemint() public {
        vm.deal(address(feeManager), 1 ether);
        console.log("Before: %d", address(feeManager).balance);
        edition.mint(address(1), 1, 1, address(0), new bytes(0));
        console.log("After: %d", address(feeManager).balance);
        assertEq(edition.totalSupply(1), 1);
    }
```

result:

```tex
Ran 1 test for test/editions/Edition.t.sol:EditionTest
[PASS] test_Freemint() (gas: 165765)
Logs:
  Before: 1000000000000000000
  After: 989400000000000000

Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.19ms
```

## Impact

Users can use the amount in the FeeManager contract to mint tokens for free.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/fees/FeeManager.sol#L366-L410

## Tool used

Manual Review

## Recommendation

Should msg.value be checked in collectMintFee if it is enough

**Comment by cu5t0mPeo** [comment]
Escalated
Trapped funds will be used for mint

**Comment by sherlock-admin3** [comment]
> Escalated
> Trapped funds will be used for mint

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
@cu5t0mPeo how there can be "unexpected amounts" in the fee manager? If other users just directly transfer tokens into the contract?

**Comment by cu5t0mPeo** [comment]
@WangSecurity The following is the explanation of the FeeManager.withdraw function (title docs):
`Withdraw any funds locked in the contract (withdraw). This is the only way to withdraw funds from the contract.`
Therefore, I believe that there are funds present in the FeeManager contract, possibly sent by other users or due to other reasons.

**Comment by cu5t0mPeo** [comment]
@WangSecurity The following is the explanation of the FeeManager.withdraw function (title docs):
Withdraw any funds locked in the contract (withdraw). This is the only way to withdraw funds from the contract.
Therefore, I believe that there are funds present in the FeeManager contract, possibly sent by other users or other reasons.

**Comment by cu5t0mPeo** [comment]
The following is the explanation of the FeeManager.withdraw function (title docs):
`Withdraw any funds locked in the contract (withdraw). This is the only way to withdraw funds from the contract.`
Therefore, I believe that there are funds present in the FeeManager contract, possibly sent by other users or due to other reasons.

**Comment by cu5t0mPeo** [comment]
@WangSecurity The following is the explanation of the FeeManager.withdraw function (title docs):
`Withdraw any funds locked in the contract (withdraw). This is the only way to withdraw funds from the contract.`
Therefore, I believe that there are funds present in the FeeManager contract, possibly sent by other users or due to other reasons.

**Comment by WangSecurity** [comment]
Yes, the contract holds funds (fees), but these are tracked and cannot be used for this. Hence, I believe the only way is if other users accidentally send it, which I believe is a user mistake. Hence, this can only happen via user mistake. Planning to reject the escalation and leave the issue as it is.

**Comment by cu5t0mPeo** [comment]
@WangSecurity However, the tracked funds can still be used for minting because the `msg.value` is not checked during the entire minting process. 
As long as there are funds in the FeeManager, users can use them for minting. You can see in the coding proof of concept that a portion of the funds are stored in the FeeManager, but users can directly use these funds to mint.

**Comment by cu5t0mPeo** [comment]
@WangSecurity Hello, could you explain what "tracked funds" means? 

I believe the issue lies in the fact that `msg.value` is unchecked. As long as there are funds in the FeeManager, even if the `msg.value` is zero, there is a risk of exploitation. The title docs clearly state that the FeeManager has locked funds that can only be withdrawn using the `withdraw` function. Therefore, I believe there are funds in the FeeManager that could potentially be exploited.

**Comment by cu5t0mPeo** [comment]
Additionally, these are locked funds that can only be withdrawn using the `withdraw` function, and they should not be used in any other way.

**Comment by cu5t0mPeo** [comment]
Additionally, these are locked funds that can only be withdrawn using the `withdraw` function. They should not be used in any other way, but in this case, it allows the locked funds to be used freely by others.

**Comment by cu5t0mPeo** [comment]
This issue is the same as https://github.com/sherlock-audit/2024-04-titles-judging/issues/157 and has been confirmed by sponsor

**Comment by WangSecurity** [comment]
Yes, you're correct, but #157 is escalated itself. Need a small clarification from the sponsor regarding this topic. Hence, either both #157 and this will be validated, either both invalidated.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cu5t0mPeo](https://github.com/sherlock-audit/2024-04-titles-judging/issues/79/#issuecomment-2109888862): rejected
